- .config/dictionaries/project.dic
- .github/CODEOWNERS
> feat: add codeowners

- hermes/Cargo.lock
- hermes/Cargo.toml
- hermes/crates/cardano-chain-follower/Cargo.toml
- hermes/crates/cardano-chain-follower/examples/basic.rs
- hermes/crates/cardano-chain-follower/src/lib.rs
This PR adds an empty `cardano-node-follower` crate.
Closes #11.
> chore: cardano-node-follower crate setup

- hermes/Earthfile
Remove `CP_SRC` UDC is a redundant command that could be replaced by the common `COPY` command.
> e.g., Closes #34 
* Removed `CP_SRC` UDC
> chore: use `COPY` command instead of `CP_SRC`

- hermes/crates/cardano-chain-follower/src/lib.rs
Helper to obtain genesis values which are required for` block.epoch(genesis: &GenesisValues)` which in my use case; is consumed from the gateway.
Gateway->Follower->Pallas.
When consuming via catalyst gateway and importing pallas and the follower to satisfy types, conflicts emerge. It is cleaner to just import the follower and add this helper method.
> feat: genesis values helper

- hermes/Cargo.toml
Switch back to using `pallas` (v0.22.0) instead of the `catalyst-pallas` fork.
Closes #63.
> chore(cardano-chain-follower): Use pallas 0.22.0 instead of catalyst-pallas

- hermes/crates/cardano-chain-follower/examples/follow_chain_updates_mithril.rs
- hermes/crates/cardano-chain-follower/src/follow.rs
Currently if the follower cannot find the mithril snapshot, it just returns an error `Error: MithrilSnapshot `
However, I was hoping we could abstract this failure and return a follower regardless i.e if it cant bootstrap from the snapshot it should return a follower which is consuming from a network. 
Maybe i'm wrong and there's an easier cleaner way, but I had to do the following to mimic the behavior described above on the consumer side.
The PR requires the `FollowerConfig` is **cloneable** for this code to work because of the move.
We can just use the below code for now (if there is no other way) and add the suggestions to the follower at a later date or address it soon on the follower side of things.
I could be way off and missing something. Please let me know.
```rust 
/// In the …
```
> feat: follower connection

- hermes/bin/src/event/queue.rs
- hermes/bin/src/reactor.rs
- hermes/bin/src/runtime_extensions/hermes/binary/mod.rs
- hermes/bin/src/runtime_extensions/hermes/cardano/mod.rs
- hermes/bin/src/runtime_extensions/hermes/cbor/mod.rs
- hermes/bin/src/runtime_extensions/hermes/cron/mod.rs
- hermes/bin/src/runtime_extensions/hermes/crypto/mod.rs
- hermes/bin/src/runtime_extensions/hermes/hash/mod.rs
- hermes/bin/src/runtime_extensions/hermes/init/mod.rs
- hermes/bin/src/runtime_extensions/hermes/json/mod.rs
- hermes/bin/src/runtime_extensions/hermes/kv_store/mod.rs
- hermes/bin/src/runtime_extensions/hermes/localtime/mod.rs
- hermes/bin/src/runtime_extensions/hermes/logging/mod.rs
- hermes/bin/src/runtime_extensions/hermes/mod.rs
- hermes/bin/src/runtime_extensions/mod.rs
- hermes/bin/src/runtime_extensions/wasi/cli/mod.rs
- hermes/bin/src/runtime_extensions/wasi/clocks/mod.rs
- hermes/bin/src/runtime_extensions/wasi/clocks/monotonic/mod.rs
- hermes/bin/src/runtime_extensions/wasi/clocks/wall/mod.rs
- hermes/bin/src/runtime_extensions/wasi/filesystem/mod.rs
- hermes/bin/src/runtime_extensions/wasi/http/mod.rs
- hermes/bin/src/runtime_extensions/wasi/io/error/mod.rs
- hermes/bin/src/runtime_extensions/wasi/io/mod.rs
- hermes/bin/src/runtime_extensions/wasi/io/streams/mod.rs
- hermes/bin/src/runtime_extensions/wasi/mod.rs
- hermes/bin/src/runtime_extensions/wasi/random/insecure/mod.rs
- hermes/bin/src/runtime_extensions/wasi/random/insecure_seed/mod.rs
- hermes/bin/src/runtime_extensions/wasi/random/mod.rs
- hermes/bin/src/runtime_extensions/wasi/random/secure/mod.rs
Thanks for contributing to the project!
Please fill out this template to help us review your changes.
List the issue numbers related to this pull request.
> e.g., Closes #123, Resolves #456  Fixes #367
Provide a clear and concise description of what the pull request changes.
Describe any breaking changes and the impact.
If applicable, add screenshots to help explain your changes.
If applicable, list any related pull requests.
> e.g., #123, #456
> fix: hermes reactor changes requested

- docs/src/architecture/08_concepts/cardano_chain_follower/overview.md
- hermes/crates/cardano-chain-follower/examples/concurrent_reads.rs
- hermes/crates/cardano-chain-follower/examples/read_block.rs
- hermes/crates/cardano-chain-follower/examples/read_block_mithril.rs
- hermes/crates/cardano-chain-follower/examples/read_block_range.rs
- hermes/crates/cardano-chain-follower/examples/read_block_range_mithril.rs
- hermes/crates/cardano-chain-follower/examples/set_read_pointer.rs
- hermes/crates/cardano-chain-follower/src/follow.rs
- hermes/crates/cardano-chain-follower/src/lib.rs
- hermes/crates/cardano-chain-follower/src/mithril_snapshot.rs
This PR fixes a bug that caused the `Follower` to get stuck when trying to set its read pointer while waiting for the next chain update.
Closes #180 
- `Follower` background task refactored to allow dropping the client and recreating it when setting the read pointer (which is needed because there seems to be no way of aborting an ongoing request to the node)
- Removed "read requests" from the follow task so the follow task is now only responsible for fetching chain updates and setting the read pointer when requested
`Follower::read_block` and `Follower::read_block_range` now spawn futures and return join handles to make it possible to make read requests concurrently while not depending on the follower's background task.
- Added `set_read_pointer` example that shows changing the follower's …
> fix(cardano-chain-follower): Refactor cardano-chain-follower to fix client concurrency bug

- hermes/crates/cardano-chain-follower/src/follow.rs
This PR fixes a bug I found while testing the Cardano Runtime Extension.
Calling `Follower::set_read_pointer` should return `Some(point)` if the requested point was found on chain (and the follower is now following from that point) and `None` if the point was not found. The current implementation always returns `None`.
> fix(cardano-chain-follower): set_read_pointer now returns None when the requested point is not found

- hermes/crates/cardano-chain-follower/src/lib.rs
This PR adds functions to get the raw bytes from a `MultiEraBlockData` value.
> chore(cardano-chain-follower): Add ways to get the raw bytes for MultiEraBlockData

- hermes/Earthfile
- hermes/bin/src/runtime_extensions/hermes/localtime/host.rs
- hermes/bin/src/runtime_extensions/hermes/localtime/localtime.rs
- hermes/bin/src/runtime_extensions/hermes/localtime/mod.rs
- hermes/bin/src/runtime_extensions/hermes/localtime/time.rs
- hermes/bin/tests/wasm-integration/main.rs
- wasm/integration-test/clocks/Earthfile
- wasm/integration-test/clocks/clocks.c
- wasm/integration-test/localtime/Earthfile
- wasm/integration-test/localtime/localtime.c
Add wasm test for `localtime` and `clocks` modules
> test: time module

- hermes/Cargo.toml
Changed `pallas` dep to the `catalyst-pallas` fork's `catalyst` branch specific commit.
`catalyst` branch would our upstream branch with all our updates which are not merged to the `pallas` main branch yet.
Also specified a commit instead of branch to make a more reliable and robust build, so any changes inside `catalyst` branch will not affect to the hermes without explicit updating of the this dependency.
> feat: Change `pallas` dep to the `catalyst-pallas` fork's `catalyst` branch specific commit

- hermes/bin/src/packaging/schema_validation.rs
- hermes/bin/src/packaging/wasm_module/config.rs
- hermes/bin/src/packaging/wasm_module/metadata.rs
- hermes/bin/src/packaging/wasm_module/mod.rs
- hermes/bin/src/packaging/wasm_module/settings.rs
Made a minor refactor. Added structs for `ConfigSchema`, `Config` and `SettingsSchema` JSON objects.
Updated WASM package test.
> refactor: Add correspondent implementation for WASM package `Config` and `Settings` JSON object.

- hermes/crates/cardano-chain-follower/src/multi_era_block_data.rs
Correcting errors and test cases in the multi-era block module.
Closes [#603](https://github.com/input-output-hk/catalyst-voices/issues/603)
* Correct test cases in the multi-era block module
* Fix the validation on the block's previous point to throw error when use `>=` point as the current one.
> fix(cardano-chain-follower): Correct multi era block tests

- hermes/bin/src/hdf5/dir.rs
- hermes/bin/src/hdf5/file.rs
- hermes/bin/src/packaging/app/mod.rs
- hermes/bin/src/packaging/package/mod.rs
- hermes/bin/src/packaging/wasm_module/mod.rs
Implemented `std::io::Read`, `std::io::Write`, `std::io::Seek` for `hdf5::File`.
Removed redundant `hdf5::File::reader` function.
#292
> feat: Implement `std::io::Read`, `std::io::Write`, `std::io::Seek` for `hdf5::File`

- hermes/bin/src/cli/run.rs
- hermes/bin/src/hdf5/dir.rs
- hermes/bin/src/hdf5/file.rs
- hermes/bin/src/vfs/bootstrap.rs
- hermes/bin/src/vfs/mod.rs
Fixed issues with the hdf5 file corruption during the hermes run.
To solve it was added flushing calls after every update of the hdf5 state.
Also fixed an issue with the mounting files during the bootstrap process.
#308 
- Refactored `VfsBoostrapper` struct, changed mount interface.
- Refactored `Vfs` struct, updated `read` and `write` interface.
- Added flushing calls on most of the methods of the `hdf5::Dir` struct.
- Added actual implementation of the `std::io::Write::flush` trait function for the `hdf5::File` struct.
> fix: VFS hdf5 file corruption, mounting app package content

- hermes/crates/cardano-chain-follower/src/data_index.rs
- hermes/crates/cardano-chain-follower/src/follow.rs
- hermes/crates/cardano-chain-follower/src/mithril_snapshot_config.rs
- hermes/crates/cardano-chain-follower/src/network.rs
- hermes/crates/cardano-chain-follower/src/stats.rs
The module already has some tests to `multi_era_block.rs` and `snapshot_id.rs`. But the rest of the module still doesn't have the test yet. So we need to create additional unit tests that don't interact with networking stuffs.
Closes #305 
Added unit tests to non-environmental interactive tests `data_index.rs`, `follow.rs`, `mithril_snapshot_config.rs`, `network.rs`, and `stats.rs`.
> test(chain-follower): Add unit tests to the overall Chain Follower module

- hermes/Cargo.toml
mithril-client to the forked fixed version
Changed version of the `mithril-client` dependency with the adding special flag to avoid `LGPL` license usage.
Closes #328
> fix: Eliminate `LGPL` license usage 

- hermes/Earthfile
- hermes/crates/cardano-chain-follower/examples/follow_chains.rs
- hermes/crates/cardano-chain-follower/src/chain_sync.rs
- hermes/crates/cardano-chain-follower/src/mithril_snapshot_config.rs
- hermes/crates/cardano-chain-follower/src/mithril_snapshot_sync.rs
- hermes/crates/cardano-chain-follower/src/mithril_turbo_downloader.rs
- hermes/crates/cardano-chain-follower/src/multi_era_block_data.rs
Add integration test to download snapshots for Chain Follower
First run
Second and later runs
Closes #311
> test(chain-follower): Add integration test to download Mithil Snapshot and validate it

- hermes/crates/cardano-chain-follower/src/follow.rs
Fix chain follower `get_block`
Closes #333
> fix: chain follower `get_block`

- hermes/crates/cardano-chain-follower/src/metadata/cip36.rs
- hermes/crates/cardano-chain-follower/src/multi_era_block_data.rs
including unit tests for
Closes #338
> test(chain-follower): Add unit tests to metadata decoding on CIP36

- .github/workflows/sync-labels.yml
- Add CI job to sync labels from `catalyst-ci`
> feat(general): add ci jobs to sync labels

- hermes/Earthfile
- wasm/examples/rust/cardano/Earthfile
- wasm/examples/rust/cardano_age/Earthfile
- wasm/examples/rust/next_century/Earthfile
- wasm/integration-test/cardano/Earthfile
- wasm/integration-test/http_reply/Earthfile
- wasm/integration-test/ipfs/Earthfile
- wasm/integration-test/sqlite/Earthfile
- wasm/integration-test/wasi-filesystem/Earthfile
- wasm/wasi/Earthfile
Bump rust-ci from v3.5.4 to v3.5.6
This will solve `libc header file not found`  for zstd direct or transitive dependency.
> fix(general): Bump rust ci to v3.5.6

- hermes/bin/src/runtime_extensions/hermes/cardano/host.rs
- hermes/bin/src/runtime_extensions/hermes/cardano/network.rs
- wasm/examples/rust/cardano/src/lib.rs
- wasm/wasi/wit/deps/hermes-cardano/api.wit
Add `get-fork` function for block resource.
This fork number is needed for creating a  [MultiEraBlock](https://github.com/input-output-hk/catalyst-libs/blob/93fd483150e2ecaf279e960fc8baf2d8babb875f/rust/cardano-blockchain-types/src/multi_era_block_data.rs#L96) that will be used later for getting RBAC registration
https://github.com/input-output-hk/hermes/issues/460
> feat(hermes): Add `get-fork` for block resource in cardano

- .config/dictionaries/project.dic
- hermes/bin/src/runtime_extensions/hermes/sqlite/connection/core.rs
- hermes/bin/src/runtime_extensions/hermes/sqlite/core.rs
- hermes/bin/tests/integration/components/sleep_component/src/lib.rs
- hermes/bin/tests/integration/tests/serial/parallel_module_execution.rs
Updates current codebase, so that parrallel writings to database does not fail.
Fixes #517
- Add `SQLITE_OPEN_NOMUTEX` flag to `open`, so sqlite works in multi-thread mode.
- Add `busy_handler` that always retries SQLITE_BUSY.
- Add liveness test for parallel execution.
- Add `enable_wal_mode` function to enable WAL mode in the future, after this [issue](https://github.com/input-output-hk/hermes/issues/521) would be resolved.
- Updated `parallel_execution` test to use database instead of file.
Updates test in [PR](https://github.com/input-output-hk/hermes/pull/488), so it uses database instead of hack with file.
> feat(hermes): parallel sql processing
